#!/bin/bash

checkoraysl(){
	ORAYSL_PID=`ps -A | grep "oraysl" | grep -v 'grep' | awk '{print $1}'`
	if [ -z "$ORAYSL_PID" ]; then
        	return
	fi
	kill -9 $ORAYSL_PID 
}
checkoraynewph(){
	ORAYNEWPH_PID=`ps -A | grep "oraynewph" | grep -v 'grep' | awk '{print $1}'`
     	if  [ -z "$ORAYNEWPH_PID" ]; then
        	return
        fi
	kill -9 $ORAYNEWPH_PID
}

if [-z "$1"]; then
	return
fi
kill $1
killall oraysl
killall oraynewph

checkoraysl
checkoraynewph
